"""initial schema

Revision ID: 3476c66d982f
Revises: 
Create Date: 2026-03-04 10:35:07.813491+00:00

Legal context: Election Campaign Financing Act, Cap. 7A (2013)
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3476c66d982f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    op.create_table('political_parties',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('abbreviation', sa.String(length=20), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('founded_date', sa.Date(), nullable=True),
    sa.Column('headquarters', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('contact_email', sa.String(length=254), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('registration_number'),
    comment='Political parties registered under Cap. 7D. Referenced throughout ECF Act Cap. 7A.'
    )
    op.create_index('ix_parties_abbreviation', 'political_parties', ['abbreviation'], unique=False)
    op.create_index('ix_parties_is_active', 'political_parties', ['is_active'], unique=False)
    op.create_index('ix_parties_name_trgm', 'political_parties', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('spending_limits',
    sa.Column('election_type', postgresql.ENUM('PRESIDENTIAL', 'GOVERNOR', 'SENATOR', 'WOMEN_REP', 'MP', 'MCA', name='election_type_enum'), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('constituency', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='KES', nullable=False),
    sa.Column('gazetted_date', sa.Date(), nullable=False),
    sa.Column('gazette_reference', sa.String(length=200), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('geographical_notes', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_spending_limits_amount_positive'),
    sa.PrimaryKeyConstraint('id'),
    comment='IEBC-gazetted spending limits per ECF Act s.18. Varied by election type, county, and constituency.'
    )
    op.create_index('ix_spending_limits_county', 'spending_limits', ['county'], unique=False)
    op.create_index('ix_spending_limits_election_type', 'spending_limits', ['election_type'], unique=False)
    op.create_index('ix_spending_limits_is_current', 'spending_limits', ['is_current'], unique=False)
    op.create_index('ix_spending_limits_type_county', 'spending_limits', ['election_type', 'county'], unique=False)
    op.create_table('candidates',
    sa.Column('full_name', sa.String(length=300), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('party_id', sa.UUID(), nullable=True),
    sa.Column('is_independent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('election_type', postgresql.ENUM('PRESIDENTIAL', 'GOVERNOR', 'SENATOR', 'WOMEN_REP', 'MP', 'MCA', name='election_type_enum'), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('constituency', sa.String(length=200), nullable=True),
    sa.Column('ward', sa.String(length=200), nullable=True),
    sa.Column('spending_limit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_contributions', sa.Numeric(precision=15, scale=2), server_default='0.00', nullable=False),
    sa.Column('total_expenditure', sa.Numeric(precision=15, scale=2), server_default='0.00', nullable=False),
    sa.Column('status', postgresql.ENUM('NOMINATED', 'CLEARED', 'ACTIVE', 'ELECTED', 'DISQUALIFIED', 'WITHDRAWN', name='candidate_status_enum'), nullable=False),
    sa.Column('iebc_registration_date', sa.Date(), nullable=True),
    sa.Column('expenditure_account_number', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['political_parties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Candidates contesting elective posts. ECF Act s.2, s.6, s.10, s.18, s.23.'
    )
    op.create_index('ix_candidates_county', 'candidates', ['county'], unique=False)
    op.create_index('ix_candidates_county_election', 'candidates', ['county', 'election_type'], unique=False)
    op.create_index('ix_candidates_election_type', 'candidates', ['election_type'], unique=False)
    op.create_index('ix_candidates_name_trgm', 'candidates', ['full_name'], unique=False, postgresql_using='gin', postgresql_ops={'full_name': 'gin_trgm_ops'})
    op.create_index('ix_candidates_party_id', 'candidates', ['party_id'], unique=False)
    op.create_index('ix_candidates_status', 'candidates', ['status'], unique=False)
    op.create_table('contributions',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='KES', nullable=False),
    sa.Column('source_type', postgresql.ENUM('INDIVIDUAL', 'CORPORATE', 'HARAMBEE', 'SELF_FUNDING', 'POLITICAL_PARTY', 'ORGANISATION', name='contribution_source_enum'), nullable=False),
    sa.Column('contributor_name', sa.String(length=300), nullable=True),
    sa.Column('contributor_id_number', sa.String(length=500), nullable=True),
    sa.Column('contributor_email', sa.String(length=254), nullable=True),
    sa.Column('contributor_phone', sa.String(length=20), nullable=True),
    sa.Column('contributor_postal_address', sa.String(length=300), nullable=True),
    sa.Column('contributor_physical_address', sa.String(length=500), nullable=True),
    sa.Column('date_received', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('receipt_number', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_from_illegal_source', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_from_public_resource', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('reported_to_iebc', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('iebc_report_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('harambee_venue', sa.String(length=500), nullable=True),
    sa.Column('harambee_date', sa.Date(), nullable=True),
    sa.Column('harambee_organiser', sa.String(length=300), nullable=True),
    sa.Column('harambee_total_collected', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('is_non_monetary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('non_monetary_description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_contributions_amount_positive'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Campaign contributions per ECF Act Part IV (s.11-17). Anonymous/illegal/public resource contributions are flagged for mandatory IEBC reporting.'
    )
    op.create_index('ix_contributions_candidate_id', 'contributions', ['candidate_id'], unique=False)
    op.create_index('ix_contributions_candidate_source', 'contributions', ['candidate_id', 'source_type'], unique=False)
    op.create_index('ix_contributions_date_received', 'contributions', ['date_received'], unique=False)
    op.create_index('ix_contributions_is_anonymous', 'contributions', ['is_anonymous'], unique=False)
    op.create_index('ix_contributions_source_type', 'contributions', ['source_type'], unique=False)
    op.create_table('expenditures',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='KES', nullable=False),
    sa.Column('category', postgresql.ENUM('VENUE', 'PUBLICITY', 'ADVERTISING', 'PERSONNEL', 'TRANSPORT', 'OTHER', name='expenditure_category_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('vendor_name', sa.String(length=300), nullable=True),
    sa.Column('vendor_contact', sa.String(length=300), nullable=True),
    sa.Column('date_incurred', sa.Date(), nullable=False),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('verified_by', sa.String(length=300), nullable=True),
    sa.Column('verification_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_expenditures_amount_positive'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Campaign expenditures per ECF Act Part III (s.5-10). Categories follow s.19(a)-(f) EXACTLY.'
    )
    op.create_index('ix_expenditures_candidate_category', 'expenditures', ['candidate_id', 'category'], unique=False)
    op.create_index('ix_expenditures_candidate_id', 'expenditures', ['candidate_id'], unique=False)
    op.create_index('ix_expenditures_category', 'expenditures', ['category'], unique=False)
    op.create_index('ix_expenditures_date_incurred', 'expenditures', ['date_incurred'], unique=False)
    op.create_index('ix_expenditures_is_verified', 'expenditures', ['is_verified'], unique=False)
    op.create_table('incidents',
    sa.Column('tracking_number', sa.String(length=20), nullable=False),
    sa.Column('incident_type', postgresql.ENUM('STATE_FUNDS', 'VEHICLE_EQUIPMENT', 'PREMISES', 'PERSONNEL', 'OTHER', name='incident_type_enum'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date_occurred', sa.Date(), nullable=False),
    sa.Column('date_reported', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('location_description', sa.String(length=500), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lng', sa.Float(), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('constituency', sa.String(length=200), nullable=True),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('party_id', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('SUBMITTED', 'UNDER_REVIEW', 'VERIFIED', 'ESCALATED', 'RESOLVED', 'REJECTED', name='incident_status_enum'), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('reporter_name', sa.String(length=300), nullable=True),
    sa.Column('reporter_email', sa.String(length=254), nullable=True),
    sa.Column('reporter_phone', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(location_lat IS NULL) OR (location_lat BETWEEN -4.7 AND 5.5)', name='ck_incidents_lat_kenya_range'),
    sa.CheckConstraint('(location_lng IS NULL) OR (location_lng BETWEEN 33.9 AND 41.9)', name='ck_incidents_lng_kenya_range'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['party_id'], ['political_parties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracking_number'),
    comment='Reported incidents of public resource misuse per ECF Act s.14. Core entity for M3 Ripoti Ubadhirifu.'
    )
    op.create_index('ix_incidents_candidate_id', 'incidents', ['candidate_id'], unique=False)
    op.create_index('ix_incidents_county', 'incidents', ['county'], unique=False)
    op.create_index('ix_incidents_county_status', 'incidents', ['county', 'status'], unique=False)
    op.create_index('ix_incidents_date_occurred', 'incidents', ['date_occurred'], unique=False)
    op.create_index('ix_incidents_incident_type', 'incidents', ['incident_type'], unique=False)
    op.create_index('ix_incidents_party_id', 'incidents', ['party_id'], unique=False)
    op.create_index('ix_incidents_status', 'incidents', ['status'], unique=False)
    op.create_index('ix_incidents_tracking_number', 'incidents', ['tracking_number'], unique=False)
    op.create_table('evidence',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_type', postgresql.ENUM('IMAGE', 'VIDEO', 'DOCUMENT', 'AUDIO', name='evidence_file_type_enum'), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('exif_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exif_gps_lat', sa.Float(), nullable=True),
    sa.Column('exif_gps_lng', sa.Float(), nullable=True),
    sa.Column('exif_device_make', sa.String(length=100), nullable=True),
    sa.Column('exif_device_model', sa.String(length=100), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Evidence files supporting incident reports. EXIF metadata used for verification (M3 Ripoti).'
    )
    op.create_index('ix_evidence_file_type', 'evidence', ['file_type'], unique=False)
    op.create_index('ix_evidence_incident_id', 'evidence', ['incident_id'], unique=False)
    op.create_table('incident_status_history',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('old_status', postgresql.ENUM('SUBMITTED', 'UNDER_REVIEW', 'VERIFIED', 'ESCALATED', 'RESOLVED', 'REJECTED', name='incident_status_enum'), nullable=True),
    sa.Column('new_status', postgresql.ENUM('SUBMITTED', 'UNDER_REVIEW', 'VERIFIED', 'ESCALATED', 'RESOLVED', 'REJECTED', name='incident_status_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(length=300), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Audit trail for incident status changes. Supports ECF Act s.21(3) timeline compliance.'
    )
    op.create_index('ix_incident_status_history_changed_at', 'incident_status_history', ['changed_at'], unique=False)
    op.create_index('ix_incident_status_history_incident_id', 'incident_status_history', ['incident_id'], unique=False)
    op.create_index('ix_incident_status_history_new_status', 'incident_status_history', ['new_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_incident_status_history_new_status', table_name='incident_status_history')
    op.drop_index('ix_incident_status_history_incident_id', table_name='incident_status_history')
    op.drop_index('ix_incident_status_history_changed_at', table_name='incident_status_history')
    op.drop_table('incident_status_history')
    op.drop_index('ix_evidence_incident_id', table_name='evidence')
    op.drop_index('ix_evidence_file_type', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('ix_incidents_tracking_number', table_name='incidents')
    op.drop_index('ix_incidents_status', table_name='incidents')
    op.drop_index('ix_incidents_party_id', table_name='incidents')
    op.drop_index('ix_incidents_incident_type', table_name='incidents')
    op.drop_index('ix_incidents_date_occurred', table_name='incidents')
    op.drop_index('ix_incidents_county_status', table_name='incidents')
    op.drop_index('ix_incidents_county', table_name='incidents')
    op.drop_index('ix_incidents_candidate_id', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('ix_expenditures_is_verified', table_name='expenditures')
    op.drop_index('ix_expenditures_date_incurred', table_name='expenditures')
    op.drop_index('ix_expenditures_category', table_name='expenditures')
    op.drop_index('ix_expenditures_candidate_id', table_name='expenditures')
    op.drop_index('ix_expenditures_candidate_category', table_name='expenditures')
    op.drop_table('expenditures')
    op.drop_index('ix_contributions_source_type', table_name='contributions')
    op.drop_index('ix_contributions_is_anonymous', table_name='contributions')
    op.drop_index('ix_contributions_date_received', table_name='contributions')
    op.drop_index('ix_contributions_candidate_source', table_name='contributions')
    op.drop_index('ix_contributions_candidate_id', table_name='contributions')
    op.drop_table('contributions')
    op.drop_index('ix_candidates_status', table_name='candidates')
    op.drop_index('ix_candidates_party_id', table_name='candidates')
    op.drop_index('ix_candidates_name_trgm', table_name='candidates', postgresql_using='gin', postgresql_ops={'full_name': 'gin_trgm_ops'})
    op.drop_index('ix_candidates_election_type', table_name='candidates')
    op.drop_index('ix_candidates_county_election', table_name='candidates')
    op.drop_index('ix_candidates_county', table_name='candidates')
    op.drop_table('candidates')
    op.drop_index('ix_spending_limits_type_county', table_name='spending_limits')
    op.drop_index('ix_spending_limits_is_current', table_name='spending_limits')
    op.drop_index('ix_spending_limits_election_type', table_name='spending_limits')
    op.drop_index('ix_spending_limits_county', table_name='spending_limits')
    op.drop_table('spending_limits')
    op.drop_index('ix_parties_name_trgm', table_name='political_parties', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('ix_parties_is_active', table_name='political_parties')
    op.drop_index('ix_parties_abbreviation', table_name='political_parties')
    op.drop_table('political_parties')
    # ### end Alembic commands ###
